// <auto-generated />
using GeekShopping.ProductAPI.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20221008023831_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "PENCIL",
                            Description = "A caneta que é sinônimo de qualidade conhecida no mundo inteiro! Corpo hexagonal que assegura o conforto na escrita e transparente para visualização da tinta. Tinta de alta qualidade, que seca rapidamente evitando borrões na escrita.",
                            ImageURL = "https://a-static.mlcdn.com.br/1500x1500/caneta-bic-cristal-azul-ponta-media-10mm-caixa-c-50un/papelarialuadecristal/12631865597/f060789ab15f16095cb635b80456fb48.jpg",
                            Name = "Caneta Azul BIC",
                            Price = 0.9m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "PENCIL",
                            Description = "A caneta que é sinônimo de qualidade conhecida no mundo inteiro! Corpo hexagonal que assegura o conforto na escrita e transparente para visualização da tinta. Tinta de alta qualidade, que seca rapidamente evitando borrões na escrita.",
                            ImageURL = "https://images-americanas.b2w.io/produtos/15726237/imagens/caneta-bic-cristal-vermelha-ponta-media-caixa-50-unidades/15726239_1_large.jpg",
                            Name = "Caneta Vermelha BIC",
                            Price = 0.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
